name: Docker Publish

on:
  # When changes are pushed to the "main" branch, run it
  push:
    branches:
      - main

  # Run every week at 0800 UTC to update the images
  schedule:
    - cron: '0 8 * * 2'

jobs:
  push:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and tag image
        run: docker build ssh/. --tag serversideup/docker-ssh

      - name: Push version image to DockerHub
        run: docker push serversideup/docker-ssh

  update_container_readme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_README_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKER_HUB_README_PASSWORD }}
        with:
          destination_container_repo: serversideup/docker-ssh
          provider: dockerhub
          short_description: 'Simple SSH container. Great for secure connections into clusters.'
          readme_file: 'README.md'