name: Docker Publish (Security Updates)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 2'  # Daily at midnight UTC

jobs:
  scan-vulnerabilities:
    runs-on: ubuntu-24.04
    outputs:
      has_vulnerabilities: ${{ steps.parse.outputs.has_vulnerabilities || inputs.force_build }}
    steps:
      - uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: 'ghcr.io/serversideup/docker-ssh'
          format: 'table'
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          ignore-unfixed: true
          exit-code: 1
          severity: 'CRITICAL,HIGH'
          hide-progress: true